print("Hello GitHub!")
print("I am learning software engineering.")
print("Hello GitHub!")
print("I am learning software engineering.")
print("I am learning teamwork with Git.")
print("I am Matiullah ZAHIN software developer.")
